apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: jitsi-meet
    repo: https://jitsi-contrib.github.io/jitsi-helm
    version: 1.5.1
    releaseName: jitsi-meet
    namespace: jitsi
    # valuesFile: values.yaml
